<a href="https://colab.research.google.com/github/assiou349/Python-for-math/blob/main/Algebre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
def LU(A):
  #dimensions
  n = A.shape[0]
  #initialisation des matrice L et U
  L = np.identity(n)
  U = np.zeros((n,n))
  #boucle sur i
  for i in range(n):
    #calcule de la i-eme ligne de u
    for j in range(i,n):
      U[i,j] = A[i,j] - np.dot(L[i,:i], U[:i,j])

    if abs(U[i,i]) < 1e-16:
      raise Exception("Pivot null")

    for j in range(i+1,n):
      L[j,i] = (A[j,i] - np.dot(L[j,:i], U[:i,i]))/U[i,i]

  return L, U

In [ ]:
A = np.random.random((10,10))
L, U = LU(A)
print(np.allclose(A, L @ U))

In [ ]:
def solve(L,U,b):
  n = L.shape[0]
  #resoud Ly = b
  y = np.zeros(n)
  for i in range(n):
    y[i] = b[i]- np.dot(L[i,:i], y[:i])
  x = np.zeros(n)
  for i in range(n-1, -1, -1):
    x[i] = (y[i] - np.dot(U[i,i+1:],x[i+1:]))/U[i,i]
  return x

In [ ]:
A = np.random.random((4,4))
b = np.random.random(4)

L, U = LU(A)
res = A @ solve(L, U, b) - b
print(np.linalg.norm(res))
print(np.allclose(A @ solve(L, U, b), b))

In [ ]:
A@solve(L,U,b)-b

In [21]:
def LU_inplace(A):
  # dimensions
  n = A.shape[0]
  for i in range(n):
    #calcule la i-eme ligne de U
    for j in range(i, n):
      A[i,j] = A[i,j]  - np.dot(A[i,:i], A[:i,j])
    if abs(A[i,i]) <1e-16:
      raise Exception("Pivot null")
    for j in range(i+1, n):
      A[j,i] = (A[j,i] -np.dot(A[j,:i], A[:i,i])) /A[i,i]
  return A

In [22]:
A = np.random.random((4,4))
L,U =LU(A)
A = LU_inplace(A)
A-L, A-U

(array([[-0.39792156,  0.32120042,  0.09315669,  0.02897995],
        [ 0.        , -1.37289547,  0.72091159,  0.14749612],
        [ 0.        ,  0.        , -0.82518089,  0.8005366 ],
        [ 0.        ,  0.        ,  0.        , -4.68152554]]),
 array([[ 0.        ,  0.        ,  0.        ,  0.        ],
        [ 1.38955998,  0.        ,  0.        ,  0.        ],
        [ 0.58554293,  0.29543347,  0.        ,  0.        ],
        [ 0.7274148 , -1.16816289,  5.39431641,  0.        ]]))

In [26]:
def solve_inplace(A, b):
  n = A.shape[0]
  #resoud Ly = b in place
  for i in range(n):
    b[i] = b[i] - np.dot(A[i,:i], b[:i])
  #resoud Ux = y
  for i in range(n-1, -1,-1):
    b[i] = (b[i] - np.dot(A[i,i+1:],b[i+1:]))/A[i,i]
  return b

In [27]:
A = np.random.random((4,4))
b = np.random.random(4)
Ak = A.copy()
bk = b.copy()

A = LU_inplace(A)
Ak  @ solve_inplace(A,b) - bk

array([-1.11022302e-16, -2.22044605e-16,  0.00000000e+00, -1.11022302e-16])

In [28]:
def det(A):
  L,U = LU(A)
  return U.diagonal().prod()

def det_inplace(A):
  LU_inplace(A)
  return A.diagonal().prod()