<a href="https://colab.research.google.com/github/assiou349/Python-for-math/blob/main/Structures_homogenes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [4]:
arr1 = list(np.arange(5, 10))

In [5]:
arr1

[np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)]

In [6]:
arr2 = np.arange(3,10,2)

In [7]:
arr2

array([3, 5, 7, 9])

In [8]:
list(arr2)

[np.int64(3), np.int64(5), np.int64(7), np.int64(9)]

In [9]:
np.linspace(2,5,10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [24]:
arr = np.arange(1,7)
arr1 =arr.reshape(3, 2)
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
arr1 =arr.reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr1 = arr1.T

In [27]:
arr1

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
#Operation matriciel
mat1 = np.array([[1,2.5,3],[5,6.1,8],[3,2,5]])
mat2 = np.array([[1,0.5,0],[0,0.9,8],[2,0,0]])

In [29]:
mat1 @ mat2

array([[ 7.  ,  2.75, 20.  ],
       [21.  ,  7.99, 48.8 ],
       [13.  ,  3.3 , 16.  ]])

In [30]:
mat1.dot(mat2)

array([[ 7.  ,  2.75, 20.  ],
       [21.  ,  7.99, 48.8 ],
       [13.  ,  3.3 , 16.  ]])

In [32]:
def diff_list(lst):
  return [lst[i+1] - lst[i] for i in range(len(lst) -1)]

In [33]:
def diff_list(lst):
  return [b -a for a, b in zip(lst, lst[1:])]

In [35]:
def dif_np(vec):
  return vec[1:] - vec[:-1]

In [40]:
a_list = [np.random.random() for _ in range(1000)]
a_np = np.random.random(1000)



In [43]:
%%time
resut = diff_list(a_list)

CPU times: user 104 µs, sys: 0 ns, total: 104 µs
Wall time: 108 µs


In [44]:
%%timeit
resut = dif_np(a_np)

2.26 µs ± 521 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [45]:
#Matrice de Vandermonde
def vdm_1(x, n):
  p =  np.size(x)
  vdm = np.empty((p, n+1))
  for i in range(p):
    for j in range(n+1):
      vdm[i,j] = x[i]**j
  return vdm

In [46]:
def vdm_2(x,n):
  p = np.size(x)
  vdm = np.empty((p, n+1))
  for k in range(n+1):
    vdm[:,k] = x**k
  return vdm

In [47]:
def vdm_3(x, n):
  p = np.size(x)
  vdm = np.ones((p,n+1))
  for j in range(1, n+1):
    vdm[:,j] = vdm[:,j-1]*x
  return vdm
